import { Vector3 } from '@dcl/sdk/math'

export const ARENA_CENTER_X = 32
export const ARENA_CENTER_Z = 32
export const ARENA_CENTER = Vector3.create(ARENA_CENTER_X, 0, ARENA_CENTER_Z)

export const ARENA_SIZE = 32
export const ARENA_HALF_SIZE = ARENA_SIZE / 2
export const ARENA_MIN_X = ARENA_CENTER_X - ARENA_HALF_SIZE
export const ARENA_MAX_X = ARENA_CENTER_X + ARENA_HALF_SIZE
export const ARENA_MIN_Z = ARENA_CENTER_Z - ARENA_HALF_SIZE
export const ARENA_MAX_Z = ARENA_CENTER_Z + ARENA_HALF_SIZE

export const ARENA_BRICK_MARGIN = 1
export const ARENA_SPAWN_MARGIN = 2

export const ARENA_BRICK_MIN_X = ARENA_MIN_X + ARENA_BRICK_MARGIN
export const ARENA_BRICK_MAX_X = ARENA_MAX_X - ARENA_BRICK_MARGIN
export const ARENA_BRICK_MIN_Z = ARENA_MIN_Z + ARENA_BRICK_MARGIN
export const ARENA_BRICK_MAX_Z = ARENA_MAX_Z - ARENA_BRICK_MARGIN

export const ARENA_SPAWN_MIN_X = ARENA_MIN_X + ARENA_SPAWN_MARGIN
export const ARENA_SPAWN_MAX_X = ARENA_MAX_X - ARENA_SPAWN_MARGIN
export const ARENA_SPAWN_MIN_Z = ARENA_MIN_Z + ARENA_SPAWN_MARGIN
export const ARENA_SPAWN_MAX_Z = ARENA_MAX_Z - ARENA_SPAWN_MARGIN

const ORIGINAL_ARENA_SIZE = 48
const ORIGINAL_ARENA_HALF_SIZE = ORIGINAL_ARENA_SIZE / 2
const ORIGINAL_WALL_LEFT_X = 1.5
const ORIGINAL_WALL_RIGHT_X = 61.5
const ORIGINAL_WALL_BOTTOM_Z = 2
const ORIGINAL_WALL_TOP_Z = 62
const ORIGINAL_WALL_LENGTH = ORIGINAL_WALL_RIGHT_X - ORIGINAL_WALL_LEFT_X

const WALL_INSET_DELTA = ORIGINAL_ARENA_HALF_SIZE - ARENA_HALF_SIZE

export const ARENA_WALL_LEFT_X = ORIGINAL_WALL_LEFT_X + WALL_INSET_DELTA
export const ARENA_WALL_RIGHT_X = ORIGINAL_WALL_RIGHT_X - WALL_INSET_DELTA
export const ARENA_WALL_BOTTOM_Z = ORIGINAL_WALL_BOTTOM_Z + WALL_INSET_DELTA
export const ARENA_WALL_TOP_Z = ORIGINAL_WALL_TOP_Z - WALL_INSET_DELTA
export const ARENA_WALL_LENGTH_SCALE = (ARENA_WALL_RIGHT_X - ARENA_WALL_LEFT_X) / ORIGINAL_WALL_LENGTH

const FLOOR_BASE_SIZE = 64
export const ARENA_FLOOR_SCALE = (ARENA_SIZE + (FLOOR_BASE_SIZE - ORIGINAL_ARENA_SIZE)) / FLOOR_BASE_SIZE
export const ARENA_FLOOR_POSITION_X = (FLOOR_BASE_SIZE - FLOOR_BASE_SIZE * ARENA_FLOOR_SCALE) / 2
export const ARENA_FLOOR_POSITION_Z = (FLOOR_BASE_SIZE - FLOOR_BASE_SIZE * ARENA_FLOOR_SCALE) / 2
export const ARENA_FLOOR_WORLD_SIZE_X = FLOOR_BASE_SIZE * ARENA_FLOOR_SCALE
export const ARENA_FLOOR_WORLD_SIZE_Z = FLOOR_BASE_SIZE * ARENA_FLOOR_SCALE
